package com.example.kafka.consumer.dto;

public enum MessageType {
    USER_REGISTERED,
    USER_UPDATED,
    USER_DELETED,
    PASSWORD_CHANGED,

    ACCOUNT_OPENED,
    MONEY_TRANSFERRED,
    LOAN_REQUESTED,
    CARD_BLOCKED,
    KYC_VERIFIED,

    PAYMENT_INITIATED,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    INVOICE_GENERATED,
    DISCOUNT_APPLIED,

    LOGIN_ATTEMPT,
    SECURITY_ALERT,
    AUDIT_LOG_EVENT,
    ACCESS_GRANTED,
    ACCESS_REVOKED,
    SESSION_EXPIRED;
}